
[en]
  # title = "Simon Heimlicher"
  LanguageName = "English"
  weight = 1

[de]
  # title = "Simon Heimlicher"
  LanguageName = "Deutsch"
  weight = 2


# [fr]
#   # title = "Simon Heimlicher"
#   LanguageName = "Français"
#   weight = 2
