en:
  LanguageName: English
  weight: 1
de:
  LanguageName: Deutsch
  weight: 2
  website:
    description: |
      Professionelle Website von Simon Heimlicher: ein leidenschaftlichen Leader, der über Führung, Organisationsentwicklung und Technologie schreibt
