goldmark:
  renderer:
    hardWraps: false
    unsafe: true
    xhtml: false
  extensions:
    typographer: false
highlight:
  codeFences: true
  guessSyntax: true
  hl_Lines: --
  lineNoStart: 1
  lineNos: true
  lineNumbersInTable: false
  noClasses: false
  tabWidth: 2
tableOfContents:
  ordered: false
  startLevel: 2
  endLevel: 2
