# FIXME: canonicalBaseURL can be set in Site but not retrieved from site.CanonicalBaseURL
canonicalBaseURL = "https://simon.heimlicher.com/"  # Include trailing slash

logoURL = "/"

# twitter = "@janedoe"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
# introDescription = "Transformation leader with a track record of leading change from organizational transformation to strategy execution at a global scale"
introDescription =   "Transformational leader with a background in technology and experience in leadership and strategy execution at a global scale"
# introURL = "about" # set the url for the 'read more' button below the introDescription, or set to false to not show the button
# description = "" # set your site's description here. will be use for home page content meta tags (seo). Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence
description = "Professional website of Simon Heimlicher – a transformational leader who writes about leadership, organizational transformation and technology."

# Alternative headline for Schema.org
alternativeHeadline = "Leadership and organizational transformation through technology"

showShare = false # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# Google analytics Id
# ga_analytics = "XXXXXXXXXX"

# Baidu analytics Id
# baidu_analytics = "XXXXXXXX"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 20

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# Top-level directories where your articles are located
# See config details here https://gohugo.io/functions/where/#mainsections
# Note: articles in these sections are styled differently:
# - The first paragraph is automatically treated as the lede
# - A drop cap is added to the second paragraph
mainSections = [
  "articles",
  "leadership",
  "organizational-transformation",
  "digital-transformation",
  "research",
  "technology"
]

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

# logo = "logos/logo.png"
# logo = "images/Heimlicher-Simon-2020-02-09-transparent-threshold.png"
logo = "images/avatar.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "right" # if you prefer right change to 'right'

# some site owners want to decide how they would like their sites to be introduced users. These settings give you as a site owner to decide how the user will view your site for the first time.
# please note that you cannot enforce both modes at the same time. i.e by enforcing one mode, you priotise it over the other (by setting it to true). enforceDarkMode will be commented out
# please also note that mode toggle UI will remain in place. That way, if a user prefers darkmode, they can have their way.
# enforceLightMode = false
# enforceDarkMode = false

# Break point to hide mobile menu and show narrow version of full navigation
screenViewBreakpointWidthMobile = "30rem"

# Break point to reset font size to regular size
screenViewBreakpointWidthNarrow = "38rem"

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# Title separator, default to |.
# titleSeparator = "|"

# Enable or disable comments globally. Default to true.
# comments = false

# Maximum number of recent posts.
numberOfRecentArticles = 3

# Maximum number of featured posts.
numberOfFeaturedArticles = 3

# Maximum number of related posts.
numberOfRelatedArticles = 5

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = true # toggle to true if you want to use custom fonts only.

# tell hugo where you store your icons e.g favicons. This is useful if you're using an apache server and there are conflicts >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory
iconsDir = "/" # without a leading forward slash

# [plausible_analytics]
# enable = false # to enable plausible analytics set to true.
# websiteDomain = "example.com" # domain name of your website, most cases same as your base url
# plausibleDomain = "plausible.io" # default is set to plausible.io, only required if plausible is selfhosted
# scritpName = "plausible" # default is set to plausible, only required if using a custome name for script

# https://themes.gohugo.io/hugo-clarity/#configuration However, sometimes you
# may need to load additional style or script files. In such cases, you can add
# custom .css and .js files by listing them in the config.toml file (see the
# snippet below). Similar to images, these paths should be relative to the
# static directory.

# FIXME: Does not work - leads to error [Error] Refused to
# execute http://localhost:1313/js/lazysizes.min.js as script because
# "X-Content-Type-Options: nosniff" was given and its Content-Type is not a
# script MIME type.

# customJS = ["js/lazysizes.min.js"]

# Added by SHZ
# Even if there are sub menu entries, do not show them in the navigation
hideSubMenus = false

# Show a button to navigate back to top ("#documentTop")
# showToTopButton = true

# Limit tags and categories to only include posts from the last x years
taxonomyMaxYears = 5

# Limit recent posts to only include posts from the last x years
recentMaxYears = 5

# Show a note indicating that an article is outdated after x years
outdatedAfterYears = 5
# Define sections whose content expires and should be flagged with a note
# after .Params.outdatedAfterYears
ephemeralSections = [
  "technology"
]

# fontFamilySans = "IBM Plex Sans"
# fontFamilySans = "Public Sans"
# fontFamilySans = "Cabin"
# fontFamilySans = "Merriweather Sans"
# fontFamilySans = "Nunito"
# fontFamilySans = "Nunito Sans"
# fontFamilySans = "Mulish"
fontFamilySans = "Source Sans 3"

# fontFamilySerif = "IBM Plex Serif"
fontFamilySerif = "Merriweather"
# fontFamilySerif = "Crimson Pro"
# fontFamilySerif = "Crimson Text"
# fontFamilySerif = "Literata"


fontFamilyMono = "DM Mono"
# fontFamilyMono = "Menlo"

# Serve font files from static instead of relying on Google Fonts servers
fontsSelfHosted = true

# Support IE 11 with JS polyfills / ponyfills
supportIE11 = true

homeSection = "_home"

footerSection = "_footer"

# sidebarTaxonomies = ["tags"]

# directories to hide from sitemap
hiddenSections = ["_error", "_home", "_footer"]

# list pages in current section in navigation for these types
navListCurrentSectionForTypes = ["vitae"]
navListCurrentSectionInSection = ["confidential", "application"]

assetDownloadFolders = ["downloads"]

themeColorLit = "hsl(42, 20%, 97%)"
themeColorDim = "hsl(208, 20%, 25%)"

[social]
  twitter = "simonheimlicher"
  github = "simonheimlicher"
  linkedin = "simonheimlicher"
  stackoverflow = "617559/simon-heimlicher"
  superuser = "69517/simon-heimlicher"

[website]
  name = "simon.heimlicher.com"
  # The year when ths website was created, this value is used in the copyright
  # notice of the footer.
  established = 1999

  [website.license]
    identifier = "CC BY-NC-ND 4.0"
    URL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[image]
  thumbnail = [
    "images/sh.com_site_thumbnail_1200x627.png",
    "images/sh.com_site_thumbnail_1200x675.png",
    "images/sh.com_site_thumbnail_1200x1200.png"
  ]

# Configuration of robots tag in head
[robots]
  index = true
  indeximages = true
  follow = true
  # Sections within which all pages will automatically include robots = noindex, nofollow
  # noIndexSections = ["confidential", "private"]
  # Sections to be listed in robots.txt as being excluded from indexing
  # CAUTION: This will cause attackers to look at these sections in particular, so do not use this parameter to hide a section
  robotsTxtDisallowSections = ["_error", "_home", "_footer"]
