minify:
  disableCSS: true
  disableHTML: true
  disableJS: true
  disableJSON: true
  disableSVG: true
  disableXML: true
  minifyOutput: false
  tdewolff:
    css:
      keepCSS2: true
      precision: 0
    html:
      keepComments: true
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepWhitespace: true
    js:
      keepVarNames: true
      precision: 0
    json:
      precision: 0
    svg:
      precision: 0
    xml:
      keepWhitespace: true
