main:
  - identifier: home
    name: home
    url: /
    weight: 50
  - identifier: leadership
    name: leadership
    url: /leadership/
    weight: 100
  - identifier: transformation
    name: transformation
    url: /transformation/
    weight: 200
  # - identifier: technology
  #   name: Technology
  #   url: /technology/
  #   weight: 500
  # - identifier: research
  #   name: Research
  #   url: /research/
  #   weight: 700
  - identifier: about
    name: about me
    url: /about/
    weight: 900
